spring:
  redis:
    timeout=60000
  jpa:
    hibernate:
      ddl-auto:validate
  liquibase:
    change-log=classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

minio:
  bucket:
    name:images